# Generated by Django 4.0 on 2021-12-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userprofile_user_userprofilecard_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilecard',
            name='user_profile',
        ),
    ]
