# Generated by Django 4.0 on 2021-12-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_userprofile_id_userprofile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uuid',
            new_name='uniqueId',
        ),
    ]
