# Generated by Django 4.0 on 2021-12-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_rename_uuid_userprofile_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uniqueId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
