# Generated by Django 4.0 on 2021-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_userprofile_member_exp_userprofile_member_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_shot',
            field=models.CharField(default='template_of_head_shot.png', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateField(null=True),
        ),
    ]
