# Generated by Django 3.2.9 on 2021-12-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_userprofile_member_exp_userprofile_member_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.TimeField(null=True),
        ),
    ]
