# Generated by Django 4.0 on 2021-12-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='static/head_shot/'),
        ),
    ]
