# Generated by Django 3.2.9 on 2021-12-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_userprofile_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_time',
        ),
    ]
