# Generated by Django 3.2.9 on 2021-12-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_userprofile_profile_photo'),
        ('member', '0012_userprofile_head_shot'),
    ]

    operations = [
    ]
