# Generated by Django 4.0 on 2021-12-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20211225_1051'),
        ('member', '0013_merge_20211225_1218'),
    ]

    operations = [
    ]
