# Generated by Django 4.0 on 2021-12-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_merge_20211226_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileCard',
        ),
    ]
